compile:
	clang++ -std=c++11 -stdlib=libc++ cabalistic.cpp -o cabalistic.o 

cabalistic0: compile
	./cabalistic.o < cabalistic_input0.txt

cabalistic1: compile
	./cabalistic.o < cabalistic_input1.txt

cabalistic2: compile
	./cabalistic.o < cabalistic_input2.txt